# Generated by Django 4.2.6 on 2024-06-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProyecto', models.CharField(max_length=100)),
                ('nombreEstudiante', models.CharField(max_length=50)),
                ('apellidoEstudiante', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=100)),
                ('nombreProfesor', models.CharField(max_length=50)),
                ('apellidoProfesor', models.CharField(max_length=50)),
            ],
        ),
    ]
