# Generated by Django 4.2.6 on 2024-06-03 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='apellidoEstudiante',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='apellidoProfesor',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='nombreEstudiante',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='nombreProfesor',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='cuentaConPatrocinio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to=settings.AUTH_USER_MODEL),
        ),
    ]
