# Generated by Django 4.2.6 on 2024-06-03 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_remove_proyecto_apellidoestudiante_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('patrocinar', 'puede patrocinar un proyecto'),), 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='profesorPatrocinador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patrocinador', to=settings.AUTH_USER_MODEL),
        ),
    ]
