# Generated by Django 4.2.6 on 2024-06-03 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_proyecto_options_proyecto_profesorpatrocinador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='cuentaConPatrocinio',
            new_name='Patrocinio',
        ),
    ]
