# Generated by Django 4.2.6 on 2024-06-03 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_cuentaconpatrocinio_proyecto_patrocinio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('Patrocinar', 'Can patrocinar proyecto'),), 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
