# Generated by Django 4.2.6 on 2024-06-03 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_proyecto_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='Patrocinio',
            new_name='patrocinio',
        ),
    ]
